### ISSUE TITLE
Primeiro contato com o cliente

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#1]
- Discutir com o cliente sobre o produto desejado e qual o seu objetivo principal.

**Comment by filypsdias** [comment]
Para melhor atender as necessidades do cliente, você pode utilizar técnicas de elicitação como:

- [ ] [Rich Picture](https://github.com/gabrielziegler3/Requisitos-2018-1/wiki/RichPicture),
- [ ] [Questionnaire](https://github.com/gabrielziegler3/Requisitos-2018-1/wiki/Questionario), *
- [x] Interview, **
- [ ] [Storytelling](https://github.com/gabrielziegler3/Requisitos-2018-1/wiki/Storytelling).

\* _Sobre a técnica de Questionário: Levante questões com o cliente para passar para a comunidade, com o objetivo de obter dados e informações relevantes que possam ser úteis para o desenvolvimento do produto._

** _Sobre a técnica de entrevista: Lembre-se de gravar toda a conversa (com a permissão do cliente) e passe ao time de desenvolvimento e gerenciamento para uma melhor elicitação de requisitos._

**Comment by MatheusFilipe95** [comment]
Estabeleci contato com a cliente e ela autorizou que nossa conversa fosse gravada vou fazer uma entrevista sobre os principais aspectos do produto.

**Comment by pAmanda** [comment]
@MatheusFilipe95 já marcaram alguma reunião?

**Comment by MatheusFilipe95** [comment]
@pAmanda  Sim, segunda feira às 16:00h. Estou aberto a sugestões de perguntas se tiverem.
