### ISSUE TITLE
Preencher quadros de conhecimento e horário

### ISSUE THREAD

**Issue by joao4018** [fga-eps-mds/2019.1-MindsY#10]
## Descrição
 
Preencher planilhas.

## Objetivo
Manter o time informado sobre disponibilidade e conhecimento.

## Tarefas

- [x] @MatheusFilipe95 
- [x] @pAmanda
- [x] @joao4018 
- [x] @filypsdias 
- [x] @deborapvilela 
- [x] @luderibeiro 
- [x] @Natilorens 
- [x] @pedroMiranda7410 
- [x] @dansousamelo

**Comment by MatheusFilipe95** [comment]
Realizei o preenchimento dos meus conhecimentos e disponibilidade.
