### ISSUE TITLE
[US18] Eu, como psicólogo, quero ter a possibilidade de visualizar o perfil de um paciente

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#100]
## Descrição

Disponibilizar as informações de um paciente específico

## Objetivo

Buscar as informações no banco e disponibilizar ao front-end de um paciente específico buscado.

## Tarefas

> Define your tasks here

- [ ] Entregar o objeto do paciente com suas respectivas informações.

**Comment by joao4018** [comment]
Sem assignees, sem milestone, e precisa mover para sprint backlog.
