### ISSUE TITLE
[US23] Eu, como psicólogo, quero ter a possibilidade de editar o perfil de um paciente

### ISSUE THREAD

**Issue by filypsdias** [fga-eps-mds/2019.1-MindsY#102]
## Descrição

Criar uma tela de edição de um paciente.

## Objetivo

Elaborar uma área destinada à edição de um paciente com suas credenciais.

## Tarefas

- [x] Criar um botão para editar paciente.
- [x] Criar tela para inserção de credenciais do paciente(nome, escolaridade, data de nascimento, reprovações, nome da mãe do paciente, nome do pai do paciente e domínio manual).
- [x] Criar botão para salvar informações.
- [x] Criar botão para voltar para tela anterior(caso o usuário deseje cancelar o cadastro).

**Comment by joao4018** [comment]
É bom relatar abertura de uma nova issue com o PO, e anexar no product backlog, pra uma proxima sprint.

**Comment by joao4018** [comment]
@MatheusFilipe95 qual issue é essa ela foi priorizada para essa sprint? @filypsdias como eu tinha comentado, essa issue foi criada por quê ? ela ta sendo desenvolvida? pode atrapalhar a coleta de métrica.

**Comment by filypsdias** [comment]
Essa issue foi priorizada para a sprint, sim. Eu e o @pedroMiranda7410 ficamos responsável por fazer ela no front e no backend. Já está em desenvolvimento, o problema é o responsável por criar as issues esqueceu de criar essa.
