### ISSUE TITLE
Separar funcionalidade de login em microservice

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#105]
## Descrição

Separar o método de login em um novo microservice á parte.

## Objetivo

Criar um micorservice responsável pelo método de login.

## Tarefas

> Define your tasks here

- [x] Criar um microservice para a funcionalidade de login.
- [ ] Autenticação por token em todos os microservices.

**Comment by pAmanda** [comment]
A api gateway vai trabalhar juntamente com o login na parte de validar os tokens passados aos recursos.
