### ISSUE TITLE
Consertar funcionalidade de consultas do microservice de paciente.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#106]
## Descrição

Reparar a consulta de pacientes.

## Objetivo

Garantir que cada psicólogo consiga pesquisar apenas os próprios pacientes.

## Tarefas

- [x] Definir a busca de pacientes pelo id de psicólogo.

**Comment by Natilorens** [comment]
A issue está com erro de português no nome.
