### ISSUE TITLE
Realizar correções no banco de dados.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#107]
## Descrição

Corrigir banco de dados de acordo com a nova definição.

## Objetivo

Realizar mudanças necessárias no banco de dados.

## Tarefas

> Define your tasks here

- [x] Definir um status para o paciente.
- [x] Trocar forein key de "responsável".
- [x] Redefinir tipo de dado de "documento" para string.
- [x] Redefinir tipo de dado de "telefone" para string.

**Comment by pAmanda** [comment]
As alterações foram feitas e comitadas.
