### ISSUE TITLE
[US5] - Implementar swagger para todos os microservices.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#108]
## Descrição

Colocar swagger em cada um dos microservices.

## Objetivo

Implementar swagger em cada microservice existente.

## Tarefas

- [ ] Colocar swagger em todos os microservices.

**Comment by pAmanda** [comment]
Como teremos um API Gateway que terá o swagger, talvez não precise implementar o swagger em todos os microservices em flask, somente na  API Gateway, já que ela que vai expor nossa API.
