### ISSUE TITLE
Reunião com cliente 25/03/2019.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#11]
## Descrição

Foi realizada uma reunião juntamente com a cliente com início: 16:00h e término: 17:20h para esclarecer os aspectos pertinentes acerca do produto de software requisitado.

## Objetivo

Obter informações de uma maneira clara e objetiva sobre o produto por meio de uma gravação de áudio(com a autorização) da cliente em uma reunião presencial.

## Tarefas
- [x] Gravar áudio da entrevista.
- [x] Compreender a definição e importância do projeto.
- [x] Perguntar sobre funcionalidades e preferências.

**Comment by joao4018** [comment]
Antes de fecharmos essa issue, gostaria que compartilha-se as anotações e áudio no drive do time.
@MatheusFilipe95  @filypsdias

**Comment by MatheusFilipe95** [comment]
Irei postar no drive, obrigado por lembrar @joao4018 .

**Comment by filypsdias** [comment]
@joao4018 @MatheusFilipe95 Em breve uma documentação mais detalhada será inserida na Wiki do projeto.
