### ISSUE TITLE
Corrigir os nomes dos components.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#110]
## Descrição

Redefinir os nomes dos components.

## Objetivo

Renomear os components para corrigir problemas de conflito.

## Tarefas

- [x] Renomear os components.

**Comment by joao4018** [comment]
Ajustado, aguardando aceitar PRs da Sprint 7 para atualizar minha branch e solicitar um novo PR.

**Comment by MatheusFilipe95** [comment]
Os PRs já foram aceitos.
