### ISSUE TITLE
Corrigir o component de rotas.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#113]
## Descrição

Arrumar o component de rotas por router link.

## Objetivo

Ajustar o component de rotas.

## Tarefas

> Define your tasks here

- [x] Correção do component de rotas.

**Comment by joao4018** [comment]
Ajustado, aguardando aceitar PRs da Sprint 7 para atualizar minha branch e solicitar um novo PR.

**Comment by MatheusFilipe95** [comment]
Os PRs já foram aceitos.
