### ISSUE TITLE
[US22] - Eu, como pisicólogo, quero ter a possibilidade de visualizar uma relatório.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#114]
## Descrição

Criar a nova funcionalidade de um gerador de relatórios.

## Objetivo

Adicionar na tela de paciente uma nova funcionalidade para um gerador de relatórios em pdf.

## Tarefas

- [x] Criar o gerador de relatórios.

**Comment by filypsdias** [comment]
O nome não deveria ser "relatório" ao invés de "avaliação"?
