### ISSUE TITLE
Criar um logotipo para o projeto em questão.

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#12]
## Descrição

> Criar um logotipo para o projeto.

## Objetivo

> Deixar o projeto mais profissional com uma identificação visual.

## Tarefas

- [x] Criação de um logotipo criativo e único.

**Comment by pAmanda** [comment]
Tarefa extra sprint, pois não foi planejada mas era importante.

**Comment by MatheusFilipe95** [comment]
Foi apresentado para a cliente, na reunião, o logotipo proposto e a mesma aprovou e elogiou a criatividade da ideia.
