### ISSUE TITLE
[TS] - Testar components existentes.

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#120]
## Descrição

Gerar testes dos components.

## Objetivo

Estabelecer cobertura de teste para os components criados.

## Tarefas

- [x] Criar teste para component de login
- [x] Criar teste para component de cadastro

**Comment by luderibeiro** [comment]
Faltam components, espero a lista de todos para completar a issue

**Comment by joao4018** [comment]
não é possível testar tudo em uma sprint, acho que esses bastam.
