### ISSUE TITLE
Criar microserviço de avaliação.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#133]
## Descrição

Desenvolver o microserviço responsável por gerenciar uma avaliação de um paciente.

## Objetivo

Iniciar e finalizar todo o microserviço de paciente.

## Tarefas

- [x] Criar e configurar o repositório do microserviço.
- [ ] Criar models.
- [ ] Mapear as models.
- [ ] Criar recursos (Resources).

**Comment by joao4018** [comment]
issue desnecessária
