### ISSUE TITLE
Fazer deploy do front-end

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#141]
## Descrição

> Fazer deploy do front-end na nuvem

## Objetivo

> Ter o front end em ambiente de produção ou homologação.

## Tarefas

- [x] Estudar como funciona o deploy e alguma plataforma na nuvem.
- [x] Fazer deploy do front-end na nuvem.

**Comment by filypsdias** [comment]
Possível bug encontrado. 
Issue aberta [aqui](https://github.com/serverless/serverless/issues/6202)

**Comment by MatheusFilipe95** [comment]
Como está o progresso com o deploy do front-end?
