### ISSUE TITLE
Aprimorar API Gateway, Incluir microsserviço Avaliação

### ISSUE THREAD

**Issue by joao4018** [fga-eps-mds/2019.1-MindsY#145]
## Descrição

Aprimorar API Gateway, Incluir microsserviço Avaliação

## Objetivo

Aprimorar API Gatetway

## Tarefas

- [x] Aprimorar API Gateway, Incluir microsserviço Avaliação
- [x] Validar o token passado antes de acessar os recursos dos microsserviços.

**Comment by MatheusFilipe95** [comment]
Foi possível realizar a validação do token?

**Comment by MatheusFilipe95** [comment]
Essa issue foi finalizada?

**Comment by pAmanda** [comment]
@MatheusFilipe95  a validação foi feita e já pode finalizar a issue.
