### ISSUE TITLE
Estudar sobre arquitetura de "microservices".

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#19]
## Descrição

> Estudar profundamente como é a arquitetura de "microservice" e compartilhar o conhecimento com o time por meio de um documento.

## Objetivo

> Ter uma boa base da arquitetura do projeto.

## Tarefas

- [x] Estudar sobre a arquitetura de "microservice".
- [x] Compartilhar conhecimento por meio de um documento.

**Comment by filypsdias** [comment]
@pAmanda, favor lembrar de evidenciar resultados dos seus estudos.
