### ISSUE TITLE
Treinamento de versionamento - GitHub

### ISSUE THREAD

**Issue by filypsdias** [fga-eps-mds/2019.1-MindsY#2]
## Descrição
* Treinamento de controle de versão usando GitHub para o time de [MDS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento).

## Objetivo
* Melhorar o conhecimento a respeito de controle de versão utilizando GitHub.

## Foco do Aprendizado
* Time de [MDS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento).

## Tarefas
- [x] Abordar diferentes tipos de termos do GitHub (commit, branch, pairing commit, pull request, etc.) - @filypsdias 
- [x] Abordar resolução de conflitos - @filypsdias 
- [x] Abordar políticas GitFlow- @pAmanda  
- [x] Mostrar todo o fluxo, desde a criação de um repositório até a submissão de um Pull Request utilizando [templates](https://github.com/fga-eps-mds/2019.1-Grupo-2/blob/master/CONTRIBUTING.md) - @filypsdias

**Comment by pAmanda** [comment]
@filypsdias o treinamento vai acontecer onde e quando?

**Comment by filypsdias** [comment]
[Repository](https://github.com/filypsdias/GitDojo)
