### ISSUE TITLE
Criar Product Backlog 

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#27]
## Descrição

Definir as issues para a Sprint 2.

## Objetivo

Gerar o escopo do trabalho semanal da Sprint 2.

## Tarefas

- [x] Designar issues a serem produzidas.
- [x] Validar formato da issues (serão histórias de usuários?)
- [x] Passar à equipe

**Comment by filypsdias** [comment]
@MatheusFilipe95, a issue diz respeito ao Product Backlog geral e não ao Sprint Backlog. Irei editar o nome da issue para melhor compreensão da equipe
