### ISSUE TITLE
Criar protótipo de baixa e alta fidelidade.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#28]
## Descrição

Desenvolver uma amostra do que será mostrado para a cliente(Juliana) do produto.

## Objetivo

Tentar replicar em forma de protótipo o produto requisitado pela cliente a fim de confirmar se os requisitos foram bem compreendidos.

## Tarefas

Funcionalidades que devem estar no protótipo de baixa fidelidade:
- [x] Login do psicólogo (Nome, Senha, Habilitação CRP).
- [x] Preenchimento das credenciais do paciente e seu histórico clínico (Anamnese, Procedimentos de Avaliação, Conclusão, Orientações). Obs: Em caso de dúvida ver os tópicos: 1, 2, 3, 4 e 5 do modelo do relatório de paciente postado no drive.

Funcionalidades que devem estar no protótipo de alta fidelidade:
- [x] Tabela com resultados finais obtidos: Instrumentos Utilizados, Escore Máximo, Escore Obtido e Classificação.
- [x] Gerar gráficos estatísticos: Resultado Ponderado nos subtestes (focar inicialmente no teste: WISC), Perfil dos Pontos Compostos.

**Comment by MatheusFilipe95** [comment]
Separei as tasks que melhor se adequam para cada tipo de protótipo com a finalidade de melhorar a visualização por parte do time de MDS.

**Comment by Natilorens** [comment]
"Gerar gráficos estatísticos: Resultado Ponderado nos subtestes (FISC), Perfil dos Pontos Compostos." Devemos gerar mesmo gráficos no protótipo de alta fidelidade, ou podemos colocar uma imagem representativa?

**Comment by MatheusFilipe95** [comment]
Pode colocar imagem mas tem que ter algo que a cliente possa interagir no protótipo de alta fidelidade.

**Comment by joao4018** [comment]
Não foi possívek finalizar na sprint 2, porém ireamoa realocae conforme a prioridade.
