### ISSUE TITLE
Treinamento da metodologia ágil

### ISSUE THREAD

**Issue by joao4018** [fga-eps-mds/2019.1-MindsY#3]
## Descrição
* Treinamento da metologia ágil que será aplicado no desenvolvimento do projeto. 

## Objetivo
* Explicar processos ágeis que serão aplicados, e deixar de forma clara para o grupo os processos ágeis adotados.

## Foco do Aprendizado
* Time de [MDS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento).

## Tarefas
- [x] Explicar as funções dos papéis para [MDS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento). (Tech Leader(Scrum Master), Product Manager (Product Owner),Devops, Arquiteto) - @joao4018  @MatheusFilipe95  @pAmanda  @filypsdias 
- [x] Explicar o processo de desenvolvimento (Sprint , backlog, daily meeting) @joao4018 
- [x] Explicar desenvolvimento de artefatos relevantes ao projeto

**Comment by filypsdias** [comment]
> Treinamento marcado juntamente com o Treinamento de GitHub #2 

* Data: 23/03/2019 14:00:00
