### ISSUE TITLE
Criar visão de deploy.

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#32]
## Descrição

> Criar visão lógica e de deploy para melhor entendimento arquitetural do projeto.

## Objetivo

> Obter melhor visualização técnica do projeto. 

## Tarefas

- [x] Criar visão de deploy.
- [x] Definir um stage de docker-compose

**Comment by filypsdias** [comment]
@pAmanda docker-compose definido.

**Comment by pAmanda** [comment]
A visão lógica foi definida erroneamente para essa sprint, pois essa visão inclui a definição e o desenho dos microservices, que é uma issue da próxima sprint,
