### ISSUE TITLE
Apresentar protótipos para a cliente.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#39]
## Descrição

Marcar uma reunião para apresentar os protótipos de alta e baixa fidelidade do projeto.

## Objetivo

Validar os protótipos com a cliente a fim de confirmar se está de acordo com as intenções da mesma.

## Tarefas

- [x] Entrar em contato com cliente.
- [x] Marcar dia da reunião.
- [ ] Classificar protótipos como: validados, não validados ou parcialmente validados.

**Comment by MatheusFilipe95** [comment]
A cliente foi alertada da necessidade da reunião. Aguardando por uma resposta.

**Comment by joao4018** [comment]
Houve resposta?

**Comment by MatheusFilipe95** [comment]
Foi apresentado para a cliente no dia de hoje 12/04.

**Comment by pAmanda** [comment]
@MatheusFilipe95 oque a cliente achou do protótipo?
