### ISSUE TITLE
Criação do Kanban

### ISSUE THREAD

**Issue by filypsdias** [fga-eps-mds/2019.1-MindsY#4]
## Descrição
* Criação do Kanban do projeto através da ferramenta Zenhub

## Objetivo
* Criar o Kanban para controle e organização de [Issues](https://github.com/fga-eps-mds/2019.1-Grupo-2/issues), Tarefas e Bugs.

## Foco da tarefa
* Time de [MDS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento). e time de [EPS](https://github.com/fga-eps-mds/2019.1-Grupo-2/wiki#equipe-de-desenvolvimentogerenciamento)

## Tarefas
- [x] Baixar extensão [ZenHub for GitHub](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=pt-BR) através da Chrome WebStore
- [x] Definir colunas do Kanban

**Comment by joao4018** [comment]
ZenHub criado de forma genérica, iremos aprimorar assim que tivermos um nome e uma definição do projeto.
Iremos trabalhar nas colunas para atender o grupo da melhor forma possível.

**Comment by pAmanda** [comment]
O zenhub vai nos ajudar também na monitoração do trabalho com os relatórios gerados por ele.
