### ISSUE TITLE
[GI01] Login de usuário no sistema

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#40]
## Descrição

Criar página de login com dados do usuário.

## Objetivo

Conseguir efetivar a entrada do usuário no software através tela de login.

## Tarefas

- [x] Login no sistema através das entradas válidas: nome e CRP.

**Comment by joao4018** [comment]
Deveria ter os critérios de aceitação.

**Comment by MatheusFilipe95** [comment]
O critério de aceitação é o cumprimento da task com as informações validadas como está especificado na mesma.

**Comment by pAmanda** [comment]
Foi criado um microsserviço para desenvolvimento da funcionalidade: https://github.com/mindsy/mindsy-microservice-authentication
