### ISSUE TITLE
[GI02] Cadastro de usuário via CRP(habilitação)

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#41]
## Descrição

Validação da CRP do usuário durante cadastro de um novo usuário no sistema. 

## Objetivo

Conferir se a inserção da CRP está no formato válido.

## Tarefas

- [x] Cadastro realizado corretamente com CRP e senha em formato válido.

**Comment by dansousamelo** [comment]
Bom dia, temos um problema para validar o CRP, existe um site para conferir o CRP de todos os estados brasileiros, link: http://cadastro.cfp.org.br/siscafweb/carregaConselho.do?1554726492145&tipoAcesso=4&s=1&tipoConsulta=pf&controle=0&sigla=cfp&ini=1 mas, no mesmo não existe uma API disponível, mandei um e-mail para a CFP(Conselho Federal de Psicologia) pedindo para disponibilizarem, ainda não obtive resposta.

Pensei em elaborar um script para acessar o site e tentar validar, mas tem o problema de resolver a captcha.
![Deepin Screenshot_20190408114502](https://user-images.githubusercontent.com/48137972/55734503-0f001000-59f6-11e9-8c94-83168609a0ab.png)
Mesmo que desse certo, o psicólogo pode ser desvinculado da profissão não pagando ou por qualquer outro problema. Teria que ocorrer uma verificação recorrente. Com isso, acho mais fácil logar pelo CRP sem verificação, o profissional deve ter ciência e ler os termos de conduta para com o software.

**Comment by MatheusFilipe95** [comment]
Pode validar apenas o formato da entrada do CRP, a verificação desenvolvemos em um estágio mais avançado da produção. Obrigado.

**Comment by pAmanda** [comment]
@dansousamelo encontrei uma api para consultar CRP, ele é paga, mas são 100 consultas gratuitas, que é oque precisamos: https://www.consultacrm.com.br

**Comment by pAmanda** [comment]
Microsserviço da funcionalidade: https://github.com/mindsy/mindsy-microservice-register
