### ISSUE TITLE
Criar tutorial de git e documento de ferramentas 

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#47]
## Descrição

> Criar um tutorial de git para pessoal de MDS e documento de ferramentas com suas respectivas versões.

## Objetivo

> Auxiliar o time de desenvolvimento sobre a utilização do git e sobre as versões das tecnologias utilizadas no projeto.

## Tarefas

- [x] Criar tutorial de git.
- [x] Criar documento sobre tecnologias utilizadas.

**Comment by joao4018** [comment]
Ajudou muito o time com esses documentos, vamos evitar muito perguntas semelhantes dos membros de MDS
