### ISSUE TITLE
Criação dos documentos EAP e TAP.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#5]
## Descrição
Elaborar e criar os documentos: Estrutura Analítica de Projeto e Termo de Abertura de Projeto.

## Objetivo
- Estabelecer as subdivisões do trabalho e das entregas do produto.
- Evidenciar a descrição do projeto assim como seus objetivos, riscos e custos.

## Tarefas
- [x] Estabelecer as entregas que irão compor o produto.
- [x] Definir a descrição do projeto.
- [x] Definir restrições do projeto.
- [x] Definir riscos do projeto.
- [x] Definir custos do projeto.
- [x] Estabelecer cronograma das entregas.

**Comment by joao4018** [comment]
Não consegui compreender os objetivos e tarefas a serem realizadas nessa issue.

**Comment by MatheusFilipe95** [comment]
Estou editando a issue para deixá-la mais clara.
