### ISSUE TITLE
Melhorar funcionalidade de cadastro

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#50]
## Descrição

Terminar pendências na parte de cadastro.

## Objetivo

Melhorar a funcionalidade de cadastro do usuário.

## Tarefas
- [x] Desenvolver a parte de front-end da tela de cadastro de usuário.
- [x] Finalizar o registro completo do usuário no banco de dados do sistema.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
