### ISSUE TITLE
Melhorar o backlog do produto

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#51]
## Descrição

Definir um padrão melhor para o backlog do produto

## Objetivo

Estabelecer uma melhor padronização no registro das user stories.

## Tarefas
- [x] Criar coluna de priorização para o backlog.
- [x] Resumir story users parecidas.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by joao4018** [comment]
Todo o backlog documentado, deve ir para o product backlog.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
