### ISSUE TITLE
[GI22] Visualizar perfil psicólogo. 

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#52]
## Descrição

Criar tela de visualização do perfil do usuário.

## Objetivo

Desenvolver a parte front-end da opção de visualizar perfil localizada no botão superior direito da navbar.

## Tarefas
Criar uma tela separada para a visualização das informações cadastradas do usuário.
A tela deve apresentar as seguintes informações:
- [x] Nome e sobrenome do usuário cadastrado.
- [x] Telefone cadastrado.
- [x] E-mail cadastrado.
- [x] Data de nascimento cadastrado.
- [x] CRP da profissão do usuário.
- [x] Foto do perfil do usuário.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
