### ISSUE TITLE
[GI14] Interface gráfica com layout de cores adequado ao tema psicologia. 

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#53]
## Descrição

Adequar o design do front-end ao tema proposto.

## Objetivo

Definir uma identidade agradável para o ambiente de uso do sistema.

## Tarefas

- [x] Decidir cores para os botões e o plano de fundo.
- [x] Ajustar a proporção do tamanho dos elementos da tela.

**Comment by joao4018** [comment]
faltou pontuação estimada.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
