### ISSUE TITLE
Finalizar protótipo.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#54]
## Descrição

Concluir pendências do protótipo.

## Objetivo

Desenvolver funcionalidades restantes do protótipo de alta fidelidade.

## Tarefas
Funcionalidades que devem constar no protótipo:

- [ ] Tabela com resultados finais obtidos: Instrumentos Utilizados, Escore Máximo, Escore Obtido e Classificação.
- [ ] Gerar gráficos estatísticos: Resultado Ponderado dos subtestes (teste WISC), Perfil dos Pontos Compostos.

**Comment by joao4018** [comment]
Ficou combinado que fariam na segunda, mas a issue não foi movida nem para in progress, aconteceu algo?

**Comment by joao4018** [comment]
Tem uma issue, da sprint 2 quando essas tarefas não foram aceitas, recomendo remover essa issue e atualizar a passada para a sprint 4.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.
