### ISSUE TITLE
[GI19] Manter psicólogo

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#55]
## Descrição

Criar telas para o processo de manter usuário.

## Objetivo

Desenvolver o front-end para atividades de manter usuário.

## Tarefas

- [x] Tela de edição das informações cadastradas.
- [x] Botões para mudança das informações cadastradas( telefone, e-mail, data de nascimento, foto do perfil).

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
