### ISSUE TITLE
Atribuir nomes significativos para variáveis.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#56]
## Descrição

Após o code review do dia 13/04 foi observado a necessidade de determinar nomes coerentes para as variáveis dos códigos apresentados.

## Objetivo

Reestruturar código feito atribuindo novas nomenclaturas para as variáveis.

## Tarefas:

- [x] Mudar o nome das variáveis localizadas na declaração das colunas do banco de dados.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
