### ISSUE TITLE
Criar views para modularizar código.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#57]
## Descrição

Foi observado no code review do dia 13/04 a necessidade de modularizar o código produzido. 

## Objetivo

Modularizar o código para melhor visualização, produção e análise da equipe.

## Tarefas

- [x] Criar views para as models do código.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.
