### ISSUE TITLE
Normalizar banco de dados.

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#58]
## Descrição

Ter uma melhor organização dos dados do banco por meio da normalização do mesmo.

## Objetivo

Aplicar regra de normalização ao código produzido.

## Tarefas

- [x] Estabelecer atributos atômicos para as tabelas do banco.

**Comment by joao4018** [comment]
Faltou o uso do ZenHub, @MatheusFilipe95  mova os card para sprint backlog o que for da sprint 4, e para o backlog o que não foi definida a milestone.

**Comment by joao4018** [comment]
Recomendo ao @luderibeiro e ao @dansousamelo entrar em contato com a @pAmanda pois na última reunião seria realizado uma mudança no banco de dados.

**Comment by MatheusFilipe95** [comment]
Os cards foram corrigidos e realocados para o correto planejamento da sprint, obrigado pelo alerta @joao4018.

**Comment by pAmanda** [comment]
@matheusbsilva não entendi o propósito dessa ISSUE. O banco de dados já está normalizado (Já se encontra na terceira forma normal).

@joao4018

**Comment by MatheusFilipe95** [comment]
A tabela do banco mostrada no code review da sprint passada não estava normalizada e após discussão foi decidido sobre a necessidade da issue.

**Comment by pAmanda** [comment]
@MatheusFilipe95 fiz algumas alterações. Dá uma olhada lá pra ver se precisa de mais alguma coisa. Talvez só preciso de alguma atualização.

**Comment by MatheusFilipe95** [comment]
Tudo certo irei fechar a issue.
