### ISSUE TITLE
Reunião de EPS 21/03/2019

### ISSUE THREAD

**Issue by joao4018** [fga-eps-mds/2019.1-MindsY#6]
## Descrição
Reunião para decisões importantes sobre o projeto (Linguagem, idioma, ferramentas).

## Objetivo
* Definir pontos importantes para se iniciar o desenvolvimento do projeto.

## Tarefas
- [x] Definir linguagem (Front e Back). 
- [x] Definir arquitetura  
- [x] Definir idioma do projeto, documentos e issues.
- [x] Criar relatório da reunião. @joao4018 
- [x] Definir ferramentas.
- [x] Definir sistema de pontos.

**Comment by joao4018** [comment]
Front-end - Angular 6.
Back-end - Flask.
Arquitetura - Microsserviços.
Ferramentas - Travis, Plan it Poker.
Pontos - Torricelli

**Comment by pAmanda** [comment]
Também montaremos o ambiente de desenvolvimento nesse dia.

**Comment by filypsdias** [comment]
@joao4018 favor adicionar à lista de ferramentas:
- [x] Visual Studio Code
- [x] WakaTime (Extensão para medição de produtividade)
- [x] ZenHub
