### ISSUE TITLE
Definir Stages da IC de Angular

### ISSUE THREAD

**Issue by filypsdias** [fga-eps-mds/2019.1-MindsY#61]
## Descrição

> Definir os estágios da integração contínua do Travis CI para projeto em Angular

## Objetivo

> Separar cada responsabilidade a um stage diferente.

## Tarefas

- [x] Definir os stages que serão usados
- [x] Incluir (configurá-los) no Travis CI

**Comment by joao4018** [comment]
falta definir os assignees @filypsdias .

**Comment by joao4018** [comment]
Não foi feito o uso de zenhub , mova o card para sprint backlog. @filypsdias

**Comment by filypsdias** [comment]
> falta definir os assignees @filypsdias .

Prezado @joao4018 , o assignee é para mim mesmo. Eu serei o responsável por essa tarefa

**Comment by filypsdias** [comment]
> Não foi feito o uso de zenhub , mova o card para sprint backlog. @filypsdias

Obrigado por recordar.

**Comment by filypsdias** [comment]
Os stages definidos para a situação atual do desenvolvimento foram de:
- [x] Build
- [x] Test

> PS: O stage de Test está comentado no arquivo [.travis.yml](https://github.com/fga-eps-mds/2019.1-MindsY/blob/develop/.travis.yml) devido a instabilidades no addon do Chrome. A correção já está sendo trabalhada.
