### ISSUE TITLE
Estudar Google Gloud Platform

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#63]
## Descrição

> Estudar como funciona o SQL cloud e como fazer o deploy das imagens docker.

## Objetivo

> Equipe estar apta a fazer deploy do projeto.

## Tarefas

- [ ] Estudar deploy do banco de dados.
- [ ] Estudar deploy de imagens docker.
- [ ] Criar documento com resumo dos estudos.

**Comment by MatheusFilipe95** [comment]
@pAmanda @filypsdias O que aconteceu com essa issue? Foi concluída? Peço para marcarem as tasks que foram feitas e mover  a issue para done antes do fechamento da sprint.

**Comment by filypsdias** [comment]
@pAmanda o banco de dados já foi inserido na nuvem?

**Comment by pAmanda** [comment]
@filypsdias Sim, foi criada uma instância do nosso banco de dados na nuvem. Já está funcionando.

**Comment by joao4018** [comment]
Como não foi possível finalizar essa issue na sprint 4, vamos remaneja-la para o backlog
