### ISSUE TITLE
Resolver pendências nos documentos da wiki

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#68]
## Descrição

> Resolver pendências em documentos.

## Objetivo

> Concluir documentos.

## Tarefas

- [x] Desenvolver tópico 2 do documento de visão.
- [x] Revisar tópico 4.3 e 7.2 documento de visão.
- [x] Fazer tópico 2 do documento de arquitetura.
- [x] Refazer diagrama de caso de uso.
- [x] Colocar fotos dos protótipos de alta e baixa fidelidade.

**Comment by dansousamelo** [comment]
Seguindo recomendações, optamos por usar gifs ao invés de fotos nos protótipos.

**Comment by pAmanda** [comment]
Muito bom @dansousamelo 
Favor lembrar de finalizar a documentação dos casos de uso (diagramas ainda incompletos).
