### ISSUE TITLE
Definir linguagens de programação para serem usadas no projeto.

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#7]
## Descrição
* Pesquisa sobre qual linguagem utilizar.

## Objetivo
* Definir linguagens de programação a serem utilizadas no projeto.

## Tarefas
- [x]  Pesquisar sobre possíveis linguagens de programação.

## Resultado
* O tema do projeto é o de Psicologia, e com isso teremos um backend e um frontend. É boa prática de programação manter o back e o front separados. Assim, pesquisamos e optamos por flask, para o backend, e angular, para o frontend. Por que? A escolha do flask (framework em python) é simples, tem uma pequena curva de aprendizado e atende o nosso projeto. O angular porque acreditamos que a maioria não tem experiência com frontend e como nós já temos uma experiência com ele, poderíamos ajudá-los melhor em futuras dúvidas. Sobre a arquitetura, faremos em "microservice".

**Comment by joao4018** [comment]
Decidido na reunião #6 de EPS do dia 21/03.

**Comment by pAmanda** [comment]
Montaremos o ambiente de desenvolvimento do time de MDS na reunião #2 do dia 23/03 às 14h na FGA.

**Comment by Natilorens** [comment]
Não tenho conhecimento nas linguagens e algumas ferramentas que serão usadas, na reunião do dia 23/03 vocês poderiam informar/indicar alguns métodos e plataformas de ensino que possam ajudar no nosso aprendizado?
