### ISSUE TITLE
Estabelecer comunicação entre o front-end e o back-end

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#71]
## Descrição

> Evoluir a escala funcional do projeto.

## Objetivo

> Promover o funcionamento do back-end com o front-end do projeto.

## Tarefas

- [x] Desenvolver o processo de requisição de cadastro do usuário.
- [x] Desenvolver o processo de requisição de login do usuário no sistema.

**Comment by filypsdias** [comment]
@pAmanda, estamos prontos para iniciar a comunicação. Como acordado, favor seguir acompanhando a equipe do Backend enquanto eu auxilio a equipe do frontend.

**Comment by pAmanda** [comment]
@filypsdias Ok!

**Comment by joao4018** [comment]
Essa issue é pra ser alocada para os membros de MDS e não de EPS, como assignees.
E a issue não esta bem escrita falta tarefas ou critérios de aceitação.

**Comment by filypsdias** [comment]
@MatheusFilipe95 , favor alocar issue para a equipe de frontend: 
- [ ] @deborapvilela 
- [ ] @pedroMiranda7410 
- [ ] @Natilorens

**Comment by joao4018** [comment]
Sugiro que inclua a seguintes tasks, Requisição de cadastro, Requisição de Login

**Comment by pAmanda** [comment]
A comunicação foi estabelecida entre o back e front, ambos já dockerizados. Foram necessárias algumas modificações no docker-compose e em alguns arquivos do front e do back.

**Comment by MatheusFilipe95** [comment]
> Essa issue é pra ser alocada para os membros de MDS e não de EPS, como assignees.
> E a issue não esta bem escrita falta tarefas ou critérios de aceitação.

Issue reformulada e corrigida conforme sugestões, obrigado.
