### ISSUE TITLE
Preparar apresentação do projeto

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#73]
## Descrição

> Preparar o material de apresentação da release 01.

## Objetivo

> Preparar documentação e treinar para a apresentação da release 01.

## Tarefas

- [x] Preparar slides.
- [x] Treinar apresentação.

**Comment by filypsdias** [comment]
@MatheusFilipe95 estarei iniciando a apresentação e em breve disponibilizarei o link.
