### ISSUE TITLE
Estabelecer comunicação do back-end com o banco de dados real.

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#75]
## Descrição

> Estabelecer comunicação do back-end com o banco de dados real.

## Objetivo

> Armazenar os dados da forma correta.

## Tarefas

- [x] Estabelecer a conexão do microsserviço com o banco de dados na nuvem.
- [x] Criar banco de dados para dev.

**Comment by joao4018** [comment]
@pAmanda  essa issue está sendo desenvolvida? ainda se encontra no sprint backlog.

**Comment by pAmanda** [comment]
@joao4018 não está sendo desenvolvida.

**Comment by pAmanda** [comment]
Finalmente, essa questão foi resolvida!

**Comment by MatheusFilipe95** [comment]
Bom trabalho.
