### ISSUE TITLE
Colocar swagger nos microsserviços prontos.

### ISSUE THREAD

**Issue by pAmanda** [fga-eps-mds/2019.1-MindsY#77]
## Descrição

> Colocar swagger nos microsserviços prontos.

## Objetivo

> Auxiliar no consumo das APIs.

## Tarefas

- [ ] Colocar swagger no ms de psychologist.
- [ ] Colocar swagger no ms de autenticação.

**Comment by filypsdias** [comment]
@pAmanda, se houver a necessidade de ajuda estou à disposição.

**Comment by pAmanda** [comment]
@filypsdias Tá bom, vou precisar.

**Comment by joao4018** [comment]
@pAmanda nao foi alocado para essa sprint né?

**Comment by filypsdias** [comment]
@joao4018 esta funcionalidade não diz respeito a essa sprint.
