### ISSUE TITLE
Configurar CI/CD inicial

### ISSUE THREAD

**Issue by filypsdias** [fga-eps-mds/2019.1-MindsY#8]
## Descrição

Desenvolver e configurar integração contínua, controle de qualidade e deploy contínuo para o projeto do time de desenvolvimento.

## Objetivo

Facilitar o processo de validação de qualidade de software do produto juntamente com seu deploy.

## Tarefas

- [ ] Configurar travis.yml
- [ ] Configurar Dockerfile
- [ ] Configurar code climate

**Comment by filypsdias** [comment]
Material útil para equipe de desenvolvimento disponível [aqui](https://docs.docker.com/install/linux/docker-ce/ubuntu/).

**Comment by pAmanda** [comment]
Muito bom! Se precisar de ajuda com Docker ou Integração Contínua pode contar comigo!
