### ISSUE TITLE
[US17] Eu, como pisicólogo, quero ter a possibilidade de cadastrar um paciente

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#86]
## Descrição

Criar a possibilidade de registrar um paciente no sistema.

## Objetivo

Implementar o processo de cadastro de um novo paciente para consulta.

## Tarefas

Implementar a correta inserção de um paciente no banco de dados contendo os seguintes atributos:

- [x] Nome do paciente.
- [x] Escolaridade.
- [x] Data de nascimento.
- [x] Reprovações.
- [x] Nome da mãe do paciente.
- [x] Nome do pai do paciente.
- [x] Domínio manual.

**Comment by joao4018** [comment]
"Psicólogo" está escrito errado.

**Comment by joao4018** [comment]
Lembrando que dentro das tarefas precisamos que essa 'US' seja entregue com TESTES.

**Comment by filypsdias** [comment]
Essa tarefa deve ser alocada na sprint 6?
