### ISSUE TITLE
[US17] Eu, como psicólogo, quero ter a possibilidade de cadastrar um paciente

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#87]
## Descrição

Criar uma tela de cadastro de um novo paciente.

## Objetivo

Elaborar uma área destinada ao cadastro de um novo paciente com suas credenciais.

## Tarefas

- [x] Criar um botão para cadastrar novo paciente.
- [x] Criar tela para inserção de credenciais do paciente(nome, escolaridade, data de nascimento, reprovações, nome da mãe do paciente, nome do pai do paciente e domínio manual).
- [x] Criar botão para salvar informações.
- [x] Criar botão para voltar para tela anterior(caso o usuário deseje cancelar o cadastro).

**Comment by joao4018** [comment]
"Psicólogo" está escrito errado.

**Comment by joao4018** [comment]
Lembrando que dentro das tarefas precisamos que essa 'US' seja entregue com TESTES.

**Comment by joao4018** [comment]
Essa issue começou a ser desenvolvida? ainda esta em sprint backlog.

**Comment by Natilorens** [comment]
Sim, já está sendo desenvolvida por mim e pelo Lude, iremos mover!
