### ISSUE TITLE
Gerar gráficos para análise das sprints 00 até 05

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#94]
## Descrição

Terminar a análise geral das sprints com a inserção de gráficos sobre detalhes do trabalho gerado.

## Objetivo

Criar gráficos com as estatísticas da performace geral das equipes de MDS e EPS ao longo das sprints até a primeira release do projeto.

## Tarefas
Gerar gráficos de:
- [x] Burndown x Velocity.
- [x] Commits x Horas.
- [x] Conhecimento x Horas.
- [ ] Faltas/presença em dailys.

**Comment by joao4018** [comment]
Tarefas erradas, não definimos ainda quais gráficos vamos realizar.

**Comment by joao4018** [comment]
optamos por não desenvolver esse tópico  Faltas/presença em dailys.

**Comment by MatheusFilipe95** [comment]
Issue reformulada devido a definição dos tipos de gráficos escolhidos.
