### ISSUE TITLE
[US18] Eu, como psicólogo, quero ter a possibilidade de visualizar o perfil de um paciente

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#97]
## Descrição

Criar tela de visualizar perfil de um paciente.

## Objetivo

Elaborar o front-end da tela de cadastro de paciente.

## Tarefas
Criar tela de visualizar credenciais do paciente:
- [ ] Imagem do paciente.
- [x] Nome do paciente.
- [x] Escolaridade.
- [x] Data de nascimento.
- [ ] Nome da mãe do paciente.
- [ ] Nome do pai do paciente.
- [ ] Reprovações.
- [x] Dominância manual.

**Comment by joao4018** [comment]
"Psicólogo" está escrito errado.

**Comment by joao4018** [comment]
Faltou pontuação! e Assignees!

**Comment by joao4018** [comment]
Milestone tbm!

**Comment by joao4018** [comment]
Lembrando que dentro das tarefas precisamos que essa 'US' seja entregue com TESTES.

**Comment by filypsdias** [comment]
Paciente tem foto? O nosso [documento](https://raw.githubusercontent.com/wiki/fga-eps-mds/2019.1-MindsY/images/logico-v3.png) não mostra isso.

**Comment by MatheusFilipe95** [comment]
> Paciente tem foto? O nosso [documento](https://raw.githubusercontent.com/wiki/fga-eps-mds/2019.1-MindsY/images/logico-v3.png) não mostra isso.

Pensei em ser opcional caso o paciente queira colocar.
