### ISSUE TITLE
[US04] Eu, como psicólogo, quero visualizar uma lista de pacientes em atendimento

### ISSUE THREAD

**Issue by MatheusFilipe95** [fga-eps-mds/2019.1-MindsY#98]
## Descrição

Criar possibilidade de listar os pacientes em atendimento.

## Objetivo

Listar pacientes em atendimento.

## Tarefas

- [x] Criar lista com nome e id dos pacientes.
- [x] Criar testes para as funcionalidade.

**Comment by joao4018** [comment]
"Psicólogo" está escrito errado.

**Comment by joao4018** [comment]
Faltou pontuação! e Assignees!

**Comment by joao4018** [comment]
Milestone tbm!

**Comment by joao4018** [comment]
Lembrando que dentro das tarefas precisamos que essa 'US' seja entregue com TESTES.

**Comment by MatheusFilipe95** [comment]
> Lembrando que dentro das tarefas precisamos que essa 'US' seja entregue com TESTES.

Tarefas atualizadas.

**Comment by Natilorens** [comment]
Já existe a função cadastrar pacientes?

**Comment by pAmanda** [comment]
@Natilorens ainda não, está sendo feito nessa sprint.

**Comment by MatheusFilipe95** [comment]
@Natilorens Está sendo desenvolvido por mim e pelo Daniel.
