### ISSUE TITLE
[US04] Eu, como psicólogo, quero visualizar uma lista de pacientes em atendimento

### ISSUE THREAD

**Issue by luderibeiro** [fga-eps-mds/2019.1-MindsY#99]
## Descrição

Entregar a lista com os pacientes cadastrados.

## Objetivo

Criar uma lista com todos os pacientes.

## Tarefas

- [x] Implementar uma lista de listagem de pacientes no sistema.

**Comment by joao4018** [comment]
Sem assignees, sem milestone, e precisa mover para sprint backlog.

**Comment by Natilorens** [comment]
Nossa issue é Back-end mesmo? Acredito que entendi errado então na reunião.

**Comment by joao4018** [comment]
@MatheusFilipe95  @filypsdias , que é responsável por essa issue?
